apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - ./k8s/dev/*

build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: pro-tuner-391513
  artifacts:
    # prod image name
    # - image: asia-south1-docker.pkg.dev/pro-tuner-391513/social-app-user-repo/user
    # dev image name
    - image: mayukh551/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    # prod image name
    # - image: asia-south1-docker.pkg.dev/pro-tuner-391513/social-app-post-repo/post
    # dev image name
    - image: mayukh551/post
      context: post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
