apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - ./k8s/ingress-service.yaml
      - ./k8s/user-depl.yaml
      # - ./k8s/post-depl.yaml

build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: pro-tuner-391513
  artifacts:
    - image: mayukh551/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .

    # - image: mayukh551/post
    #   context: post
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
