apiVersion: skaffold/v2alpha3
kind: Config

deploy:
  kubectl:
    manifests:
      - ./k8s/dev/user-depl.yaml
      - ./k8s/dev/post-depl.yaml
      - ./k8s/dev/feed-depl.yaml

build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: pro-tuner-391513
  artifacts:
    # //************************************ User Image Build ***********************************
    # prod image name
    # - image: asia-south1-docker.pkg.dev/pro-tuner-391513/social-app-user-repo/user
    # dev image name
    - image: mayukh551/user
      context: user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .

    # //************************************ Post Image Build ***********************************

    # prod image name
    # - image: asia-south1-docker.pkg.dev/pro-tuner-391513/social-app-post-repo/post
    # dev image name
    - image: mayukh551/post
      context: post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .

    # //************************************ Feed Image Build ******************************

    - image: mayukh551/feed
      context: feed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/***/*.ts"
            dest: .
