# Postgres deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
  namespace: social-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_USER
              value: john
            - name: POSTGRES_DB
              value: mydb

---
# Cluster IP service for postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres-srv
  namespace: social-app
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432